// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import GrapejsEditorController from "./grapesjs_editor_controller"
application.register("grapesjs-editor", GrapejsEditorController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)
