puts "=== Verifying Pixelia Setup ==="
puts ""
puts "Jobs loaded:"
puts "  - #{Ecommerce::BaseSyncJob}"
puts "  - #{Ecommerce::ShopifySyncJob}"
puts "  - #{Ecommerce::WoocommerceSyncJob}"
puts "  - #{Ecommerce::SyncAllStoresJob}"
puts ""
puts "Services loaded:"
puts "  - #{Ecommerce::ShopifySyncService}"
puts "  - #{Ecommerce::WoocommerceSyncService}"
puts ""
puts "Policies loaded:"
puts "  - #{ClientPolicy}"
puts "  - #{UserPolicy}"
puts "  - #{ProjectPolicy}"
puts "  - #{EcommerceStorePolicy}"
puts "  - #{LeadPolicy}"
puts ""
puts "Controllers loaded:"
puts "  - #{Admin::BaseController}"
puts "  - #{Admin::DashboardController}"
puts "  - #{Admin::ClientsController}"
puts "  - #{Admin::UsersController}"
puts "  - #{Admin::ProjectsController}"
puts "  - #{Admin::LeadsController}"
puts ""
puts "Database:"
puts "  Clients: #{Client.count}"
puts "  Users: #{User.count}"
puts "  Projects: #{ActsAsTenant.without_tenant { Project.count }}"
puts "  EcommerceStores: #{ActsAsTenant.without_tenant { EcommerceStore.count }}"
puts "  Leads: #{Lead.count}"
puts ""
puts "=== All checks passed! ==="
